- inc/cper.hpp
- src/main.cpp
pull-in PCIe dump support in OOB Crashdump feature.
PCIE dump is harvested using BLOCK_ID = 33 of the existing APML mailbox commands 5Bh and 5Ch.
The APML responses from is posted to the new DBG LOG section in the CPER definition
> Harvest PCIE dump

- inc/cper.hpp
- src/main.cpp
The CPUID instruction is executed with EAX=1 to get the o/p in eax ,ebx,ecx and edx which has the details Model, Family, and stepping information.
> Fix CPUID in CPER file

- inc/cper.hpp
- src/main.cpp
1. Major number field is updated for Mi300 platform. If the Model number is 0x80 or 0x90 , then the major number field will display 2 for Program ID
> Add Major number for MI300

- inc/cper.hpp
- src/main.cpp
1. Changed Fatal error CPER section size to 65536b which was 65680b previously.
2. Added BoardID change which is removed as part of platform-specific code.
3. Write 1 to the bit of the error source to clear the RAS status register instead of writing 1 all the time
> Change CPER section size

- src/main.cpp
Moving FindNumberOfCpu() API before PlatformInitialization as it is causing functionality issues
> Find number of CPU's before platform initialization

- src/runtime_errors.cpp
PMFW does not honor a PCIe OOB reporting request if AER is not enabled. If PCIe error reporting is desired, then the BMC should keep reissuing the PCIe AER enable request until it see a success response. Hence SetRasOobConfig command is retried for 300 seconds until the command is success once APML is up.
> Add retries for setrasoobconfig command

- inc/ras.hpp
- src/runtime_errors.cpp
Increasing the SetRasOobConfig retries to 15 minutes as the 2P systems take more time to enable PCIE AER
> Increase the Set Ras Oob Config retries

- src/fatal_error.cpp
Fixed typo in system call to register dump script
Fixes: FWDEV-65553
> Fix typo in HPM dump script invocation

- src/main.cpp
To create proper CPER files, BlockID need to be selected based on based on platform type.
> amd-ras: modify BlockID selection for MI300A/C to create CPER files

- inc/cper.hpp
- inc/ras.hpp
- src/fatal_error.cpp
- src/main.cpp
- src/runtime_errors.cpp
- src/write_cper_data.cpp
1. Added error threshold overflow feature for runtime errors. The error threshold overflow is supported for runtime MCA, DRAM CECC and PCIE errors.
2. The input argument for SetRasOobConfig command is changed in the latest PPR which has polling mode or interrupt mode as input argument.
3. Updated the input argument for SetRasOobConig command to integrate the apml library 3.3.0.
> Error threshold overflow feature enablement

- inc/cper.hpp
- inc/ras.hpp
- src/main.cpp
- src/runtime_errors.cpp
- src/write_cper_data.cpp
Added DBG_LOG_ID = 23 in Turin ADDC Crashdump flow.
Add event log when a CPER file is generated for fatal errors.
Add retries if the BMC_RAS_SET_ERR_THRESH command failed.
Set PCI OOb error reporting enable bit via 0x61 command prior
to sending PCI error threshold enable command(0x63).
Signed-off-by: Abinaya Dhandapani <adhandap@amd.com>
> Add debug log ID 23 to crashdump flow

- inc/Config.hpp
- inc/cper.hpp
- inc/ras.hpp
- src/Config.cpp
- src/dbus_ras.cpp
- src/fatal_error.cpp
- src/main.cpp
- src/runtime_errors.cpp
Added the new RAS configuration parameters AifsArmed and AifsSigId.
If AifsArmed is true and valid mca bank is > 0 , Check if current-failure SigID matches any of the AifsSigId entries in the AifsSignatureIdList. If SigID matches, start the AIFS flow.
Signed-off-by: Abinaya Dhandapani <adhandap@amd.com>
> Implement local AIFS trigger in amd-ras service

- inc/Config.hpp
- src/Config.cpp
- src/dbus_ras.cpp
- src/main.cpp
- src/runtime_errors.cpp
Rename the below properties in /var/lib/amd-ras/config_file to avoid confusion and distinguish from MaxInterruptRate.
DramCeccErrCounter > DramCeccErrThresholdCnt
McaErrCounter > McaErrThresholdCnt
PcieAerErrCounter > PcieAerErrThresholdCnt
> ErrCounter rename to ThresholdCnt in BMC config file

- inc/Config.hpp
- inc/cper.hpp
- src/Config.cpp
- src/dbus_ras.cpp
- src/fatal_error.cpp
- src/main.cpp
- src/runtime_errors.cpp
- src/write_cper_data.cpp
Change the APML offset from 44 to 52 to read PCIE root error status.
> Fix APML offset to read PCIE root error status

- src/main.cpp
The APML initialization is been done using the RUNTIME_ERR_VALIDITY_CHECK command which is not supported in Genoa.  So, use processor info command to check if the APML is up when the RUNTIME_ERR_VALIDITY_CHECK command returns not supported error code.
> Genoa: Perform APML initialization using PROC_INFO APML command

- .clang-format
- .prettierrc.yaml
- LICENSE
- OWNERS
- README.md
- config/ras_config.json
- include/config_manager.hpp
- meson.build
- service_files/com.amd.RAS.service
- src/config_manager.cpp
- src/main.cpp
- Added README.md with project overview.
- Added OWNERS file to define project ownership and contributors.
- Added LICENSE file to specify project licensing terms.
- Added clang-18 formatter and prettier
Interface:
com.amd.RAS.Configuration           interface -          -                                        -
.GetAttribute                       method    s          v                                        -
.SetAttribute                       method    sv         -                                        -
.RasConfigTable                     property  a{s(ssvx)} 9 "AifsArmed" "com.amd.RAS.Configurat... emits-change writable
org.freedesktop.DBus.Introspectable interface -          -                                        -
.Introspect                         method    -          s …
> Initial patch for RAS configuration settings

- inc/cper.hpp
- inc/ras.hpp
- src/fatal_error.cpp
- src/main.cpp
1. Add redfish event log if the APML_ALERT_L is asserted due to MCE error.
2. clear the RMI_ALERTSTATUS [0x10 ~ 0x1f] [0x50 ~ 0x5f] at the time of APML_ALERT_L assertion in addition to clearing the RMI_ALERTSTATUS register during initialization.
3. MCE status register occupies 8 bits from C0 as it supports 256 cores. Clear 8 bits of MCE Status register if set.
4.  During a syncflood ( in certain type of errors such as CXL protocol errors) if BMC_RAS_MCA_VALIDITY_CHECK()
returns 0 , do not exit the crashdump flow. Continue harvesting the additional debug log ID dumps and create
the CPER record.
> Clear RMI_ALERTSTATUS register during ALERT_L assertion

- include/crashdump_manager.hpp
- src/crashdump_manager.cpp
Changed CrashdumpInterface to inherit from
sdbusplus::server::object_t<CrashdumpBase> using virtual inheritance. This ensures objectMapper correctly detects dynamically created object paths, which was previously failing.
Tested fields: Verified in Congo platform.
> Fix objectMapper detection of dynamic paths

- src/apml_manager.cpp
- src/utils/cper.cpp
Updated the logic to correctly detect Non-MCA shutdown errors by checking bit 6 of the RAS Status Register, instead of the previously incorrect check on bit 0.
Set the NotificationType in the event header to gEfiEventNotificationTypeMceGuid, enabling proper handling of fatal error notifications
> Bug fixes in the crashdump event flow

- include/config_manager.hpp
- include/utils/cper.hpp
- src/config_manager.cpp
- src/utils/cper.cpp
- Integrated DeleteAll D-Bus interface.
- Implemented deleteAll() to remove node-specific and .cper files.
- Cleared crashdump D-Bus interfaces if CPER files are deleted.
Tested fields: Verified in congo system
> Add DeleteAll interface and implement CPER file cleanup
